[package]
name = "common"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.104"
axum = "0.8.9"
config = "0.15.25"
dotenvy = "0.15.7"
serde = "1.0.229"
serde_json = "1.0.151"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["json", "env-filter"] }
